export const ACTIONS = {
    ADD_TO_CART: 'ADD_TO_CART',
    REMOVE_ONE_FROM_CART: 'REMOVE_ONE_FROM_CART',
    SUM_PRICE: 'SUM_PRICE',
    SUBST_PRICE: 'SUBST_PRICE',
    ADD_COUNTER: 'ADD_COUNTER',
    SUBST_COUNTER: 'SUBST_COUNTER',
    RESET_CART: 'RESET_CART',
};